
#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123456@127.0.0.1:8761/eureka/
  instance:
    # 在Eureka中显示真实IP:端口号
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 超时时间> ribbon超时时间*3
            timeoutInMilliseconds: 12001

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


# 自定义配置
pgy:
  # 业务配置
  biz:
    # 业务地址
    host: http://tapi.huashuangtec.com
