spring:
  application:
    name: eureka-server
  profiles:
    active: eureka-server1
  #安全信息
  security:
    user:
      #账号
      name: admin
      #密码
      password: admin123456


---
spring:
  profiles: eureka-server1

server:
  port: 8761

eureka:
  server:
    # 自我保护机制
    enable-self-preservation: false
  instance:
    # 指定主机名称
    hostname: eureka-server1
    # 每隔10s发送一次心跳
    lease-renewal-interval-inSeconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30
  client:
    # 由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: false
    # 服务地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@server2:8762/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@server3:8763/eureka/

---
spring:
  profiles: eureka-server2

server:
  port: 8762

eureka:
  server:
    # 自我保护机制
    enable-self-preservation: true
  instance:
    # 指定主机名称
    hostname: eureka-server2
    # 每隔10s发送一次心跳
    lease-renewal-interval-inSeconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30
  client:
    # 由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: false
    # 服务地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@server1:8761/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@server3:8763/eureka/


---
spring:
  profiles: eureka-server3

server:
  port: 8763

eureka:
  server:
    # 自我保护机制
    enable-self-preservation: true
  instance:
    # 指定主机名称
    hostname: eureka-server3
    # 每隔10s发送一次心跳
    lease-renewal-interval-inSeconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30
  client:
    # 由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: false
    # 服务地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@server1:8761/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@server2:8762/eureka/